name: Migrate Bitbucket Repos to GIT

on:
  workflow_dispatch: # Trigger manually or set up a schedule if needed

jobs:
  migrate-repos:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "Your GIT Username"
          git config --global user.email "your-email@example.com"

      - name: Read Repos from Text File and Migrate
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
          BITBUCKET_APP_PASSWORD: ${{ secrets.BITBUCKET_APP_PASSWORD }}
        run: |
          # Read repos from text file
          while read -r bitbucket_repo_url; do
            # Extract the repo name from the URL by taking the last part after the final '/'
            repo_name=$(basename -s .git "$bitbucket_repo_url")

            echo "Migrating repository: $repo_name from $bitbucket_repo_url"

            # Create a new GIT repository using the GIT API
            curl -H "Authorization: token $GIT_TOKEN" \
              -d "{\"name\":\"$repo_name\", \"private\":true}" \
              https://api.GIT.com/user/repos

            # Clone the Bitbucket repository
            git clone --mirror "https://$BITBUCKET_USERNAME:$BITBUCKET_APP_PASSWORD@$bitbucket_repo_url"

            cd "$repo_name.git"

            # Add GIT as a remote
            git remote add GIT "https://$GIT_TOKEN@GIT.com/your-GIT-username/$repo_name.git"

            # Push all branches and tags to GIT
            git push --mirror GIT

            # Clean up
            cd ..
            rm -rf "$repo_name.git"

            echo "Migration of $repo_name completed."
          done < bitbucket_repos.txt  # Read from the text file
