name: Migrate Bitbucket Repos to GitHub

on:
  workflow_dispatch: # Trigger the workflow manually

jobs:
  migrate-repos:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "Your GitHub Username"
          git config --global user.email "your-email@example.com"

      - name: Create Repos and Migrate from Bitbucket
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
          BITBUCKET_APP_PASSWORD: ${{ secrets.BITBUCKET_APP_PASSWORD }}
        run: |
          # List of Bitbucket repositories (in format: 'repo_name' and 'bitbucket_repo_url')
          repos=(
            "repo1 https://bitbucket.org/user/repo1.git"
            "repo2 https://bitbucket.org/user/repo2.git"
            # Add more repositories here
          )

          # Iterate over each repo and migrate
          for repo_info in "${repos[@]}"; do
            repo_name=$(echo $repo_info | awk '{print $1}')
            bitbucket_repo_url=$(echo $repo_info | awk '{print $2}')

            echo "Migrating repository: $repo_name from $bitbucket_repo_url"

            # Create a new GitHub repository using the API
            curl -H "Authorization: token $GITHUB_TOKEN" \
              -d "{\"name\":\"$repo_name\", \"private\":true}" \
              https://api.github.com/user/repos

            # Clone the Bitbucket repository
            git clone --mirror "https://$BITBUCKET_USERNAME:$BITBUCKET_APP_PASSWORD@$bitbucket_repo_url"

            cd "$repo_name.git"

            # Add GitHub as a remote
            git remote add github "https://$GITHUB_TOKEN@github.com/your-github-username/$repo_name.git"

            # Push all branches and tags to GitHub
            git push --mirror github

            # Clean up
            cd ..
            rm -rf "$repo_name.git"

            echo "Migration of $repo_name completed."
          done
