name: Auto-convert Jenkins to ADO YAML + Open PRs

on:
  workflow_dispatch:
    inputs:
      repos_file:
        description: "Path to a newline-separated file of repo paths or Git URLs"
        required: false
        default: "migrate-repo-list.txt"
      targets_file:
        description: "CSV mapping overrides (optional). If omitted, auto-resolve ADO targets."
        required: false
        default: "ado-targets.csv"
      ado_org:
        description: "ADO org slug (NOT a URL). Example: VI20040428"
        required: true
        default: "VI20040428"
      ado_project:
        description: "Default ADO project (for auto resolution & repo creation)"
        required: true
        default: "PartsUnlimitedTest"
      autodiscover_projects:
        description: "Scan all projects in org to find matching repo"
        required: false
        default: false
        type: boolean
      create_if_missing:
        description: "Create ADO repo if not found"
        required: false
        default: true
        type: boolean
      python_version:
        description: "Python version"
        required: false
        default: "3.11"

permissions:
  contents: read

concurrency:
  group: auto-convert-jenkins-to-ado
  cancel-in-progress: false

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.collect.outputs.repos }}
    steps:
      - uses: actions/checkout@v4

      - id: collect
        shell: bash
        run: |
          set -euo pipefail
          FILE="${{ inputs.repos_file }}"
          [[ -f "$FILE" ]] || { echo "Repos file not found: $FILE"; exit 1; }
          python - <<'PY' > /tmp/repos.json
          import json, pathlib
          p = pathlib.Path("${{ inputs.repos_file }}")
          items = []
          for line in p.read_text(encoding="utf-8", errors="ignore").splitlines():
              s = line.strip()
              if not s or s.startswith("#"):
                  continue
              items.append(s)
          print(json.dumps(items))
          PY
          echo "repos=$(cat /tmp/repos.json)" >> "$GITHUB_OUTPUT"

  convert:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    env:
      # GitHub source cloning (private repos)
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}             # PAT with repo:read on source repos
      GIT_USERNAME: ${{ secrets.GIT_USERNAME }}    # optional; default is x-access-token if unset
      # Azure DevOps (for later PR creation or if your converter needs it)
      ADO_PAT: ${{ secrets.ADO_PAT }}
    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJSON(needs.prepare-matrix.outputs.repos) }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Git (Dynamic Username and Email)
        run: |
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"

      # Belt-and-suspenders: force-auth any https://github.com/ clone via PAT
      - name: Force-auth GitHub clones
        run: |
          test -n "${GIT_TOKEN:-}" || { echo "GIT_TOKEN not set; ensure secrets.GIT_TOKEN exists"; exit 1; }
          git config --global url."https://${GIT_USERNAME:-x-access-token}:${GIT_TOKEN}@github.com/".insteadOf "https://github.com/"

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}
          cache: pip
          cache-dependency-path: tools/requirements.txt

      - name: Install converter deps
        run: |
          python -m pip install --upgrade pip
          # If you have a requirements.txt for the converter, prefer:
          pip install -r tools/requirements.txt
          
      - name: Create output folder
        id: pathing
        shell: bash
        run: |
          set -euo pipefail
          RAW="${{ matrix.repo }}"
          SLUG="$(echo "$RAW" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9._-' '-' | sed 's/^-*//;s/-*$//')"
          OUTDIR="out/${SLUG}"
          mkdir -p "$OUTDIR"
          echo "slug=$SLUG" >> "$GITHUB_OUTPUT"
          echo "outdir=$OUTDIR" >> "$GITHUB_OUTPUT"

      - name: Run auto-converter
        shell: bash
        run: |
          set -euo pipefail
          python tools/auto_convert_repo_to_ado_yaml.py \
            --repo "${{ matrix.repo }}" \
            --out-dir "${{ steps.pathing.outputs.outdir }}" \
          | tee "${{ steps.pathing.outputs.outdir }}/summary.json"
          test -f "${{ steps.pathing.outputs.outdir }}/azure-pipelines.yml"

      - uses: actions/upload-artifact@v4
        with:
          name: ado-yaml-${{ steps.pathing.outputs.slug }}
          path: |
            ${{ steps.pathing.outputs.outdir }}/azure-pipelines.yml
            ${{ steps.pathing.outputs.outdir }}/summary.json
          if-no-files-found: error
          retention-days: 14

  open-prs:
    needs: convert
    runs-on: ubuntu-latest
    env:
      ADO_PAT: ${{ secrets.ADO_PAT }}
      GIT_USERNAME: ${{ secrets.GIT_USERNAME }}    # for git commit identity
      GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Git (Dynamic Username and Email)
        run: |
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}
          cache: pip
          cache-dependency-path: tools/requirements.txt

      - name: Install PR deps
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/requirements.txt

      - uses: actions/download-artifact@v4
        with:
          pattern: ado-yaml-*
          merge-multiple: true
          path: pr_inputs

      - name: Open PRs in Azure DevOps
        shell: bash
        run: |
          set -euo pipefail
          test -n "${ADO_PAT:-}" || { echo "Missing ADO_PAT"; exit 1; }
          python tools/ado_open_pr.py \
            --in-root pr_inputs \
            --ado-org "${{ inputs.ado_org }}" \
            --ado-project "${{ inputs.ado_project }}" \
            --targets "${{ inputs.targets_file }}" \
            --autodiscover-projects "${{ inputs.autodiscover_projects }}" \
            --create-if-missing "${{ inputs.create_if_missing }}"
