name: Migrate Bitbucket Repos to GitHub

on:
  workflow_dispatch:

jobs:
  migrate-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install tree and git-filter-repo
        run: |
          sudo apt-get update
          sudo apt-get install tree -y
          # Install git-filter-repo
          sudo apt-get install python3-pip -y
          pip3 install git-filter-repo

      - name: Set up Git (Dynamic Username and Email)
        run: |
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"

      - name: Read Repos from Text File and Migrate (excluding artifacts/large files)
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
          BITBUCKET_APP_PASSWORD: ${{ secrets.BITBUCKET_APP_PASSWORD }}
        run: |
          while read -r bitbucket_repo_url; do
            repo_name=$(basename -s .git "$bitbucket_repo_url")
            echo "Migrating repository: $repo_name from $bitbucket_repo_url"

            # Create new GitHub repo
            curl -H "Authorization: token $GIT_TOKEN" \
              -d "{\"name\":\"$repo_name\", \"private\":true}" \
              https://api.github.com/user/repos

            # Clone Bitbucket repo (mirror)
            git clone --mirror "https://$BITBUCKET_USERNAME:$BITBUCKET_APP_PASSWORD@$bitbucket_repo_url"
            cd "$repo_name.git"

            # === FILTER: Remove build artifacts and large files ===

            # Exclude folders: build/, dist/, .cache/
            # Exclude files larger than 10MB (example limit)
            git filter-repo \
              --path-glob 'build/**' --path-glob 'dist/**' --path-glob '.cache/**' --invert-paths \
              --strip-blobs-bigger-than 10M

            # Add GitHub remote
            git remote add github "https://${{ secrets.GIT_TOKEN }}@github.com/${{ secrets.GIT_USERNAME }}/$repo_name.git"

            # Push filtered history
            git push --mirror github

            echo "Folder structure of the migrated repository:"
            tree .

            cd ..
            rm -rf "$repo_name.git"
            echo "Migration of $repo_name completed."
          done < bitbucket_repos.txt
